from dataclasses import dataclass

class DatainjestionArtifact:
    feature_store_file_path:str
    test_file_path:str
    train_file_path:str


class DataValidationArtifact:...
class DataTranformaitonArtifact:...
class ModeltrainerArtifact:...
class ModelevaluationArtifact:...
class ModelPusherArtifact:...