class Datainjestionconfigeraiton:...
class DataValidationconfigeration:...
class DataTranformaitonconfigeration:...
class Modeltrainerconfigeration:...
class Modelevaluationconfigeration:...
class ModelPusherConfigeration:...